# Generated by Django 6.1.1 on 2026-09-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caserecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='caserecord',
            name='assigned_detective',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Closed', 'Closed')], default='Open', max_length=30),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=20),
        ),
    ]
