# Generated by Django 6.1.1 on 2026-09-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_caserecord_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caserecord',
            old_name='assigned_detective',
            new_name='assigned_officer',
        ),
    ]
